services:
  api-node:
    # labels:
    #   shipyard.route: '/api/node/'
    #   shipyard.route.rewrite: true
    image: api-node
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:123@db:5432/postgres
    networks:
      - backend
    ports:
      - 3000:3000
    restart: unless-stopped

  db:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
    networks:
      - backend
    ports:
      - 5433:5432
volumes:
  pgdata:
networks:
  backend: